# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.cache/wt [current_project]
set_property parent.project_path F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/Accumulator.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/BUF1.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/BUF2.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/Bias_ROM.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/Comparator.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/FC_Bias_ROM.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/FC_Controller.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/FC_Layer.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/FIFO.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/MAC.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/MaxPooling_ReLU.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/Max_finder.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/PE.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/PE_Array.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/Sliding_Window.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/acc.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/glbl_controller.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/matmul.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/mul.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/single_port_bram.sv
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/top.sv
}
read_verilog -library xil_defaultlib F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/TDP.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc
set_property used_in_implementation false [get_files F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
