@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Sun Sep 29 03:11:34 +0900 2024
=======
REM Generated by Vivado on Mon Sep 23 23:55:38 +0900 2024
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xelab -wto d37c42bbbd01400a9ccd620d5c86f79f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_CombinedIP_behav xil_defaultlib.tb_CombinedIP xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto d37c42bbbd01400a9ccd620d5c86f79f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_CombinedIP_behav xil_defaultlib.tb_CombinedIP xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto d37c42bbbd01400a9ccd620d5c86f79f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_DigInPort_behav xil_defaultlib.tb_DigInPort xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto d37c42bbbd01400a9ccd620d5c86f79f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_DigInPort_behav xil_defaultlib.tb_DigInPort xil_defaultlib.glbl -log elaborate.log
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
