@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Sun Sep 29 03:11:33 +0900 2024
=======
REM Generated by Vivado on Mon Sep 23 23:55:37 +0900 2024
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xvlog --incr --relax -prj tb_CombinedIP_vlog.prj"
call xvlog  --incr --relax -prj tb_CombinedIP_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj tb_DigInPort_vlog.prj"
call xvlog  --incr --relax -prj tb_DigInPort_vlog.prj -log xvlog.log
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
