@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Sun Sep 29 03:03:04 +0900 2024
=======
REM Generated by Vivado on Mon Sep 23 23:51:05 +0900 2024
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xsim tb_CombinedIP_behav -key {Behavioral:sim_1:Functional:tb_CombinedIP} -tclbatch tb_CombinedIP.tcl -view E:/SimLab01/SimLab01/tb_WB_behav.wcfg -log simulate.log"
call xsim  tb_CombinedIP_behav -key {Behavioral:sim_1:Functional:tb_CombinedIP} -tclbatch tb_CombinedIP.tcl -view E:/SimLab01/SimLab01/tb_WB_behav.wcfg -log simulate.log
=======
echo "xsim tb_DigInPort_behav -key {Behavioral:sim_1:Functional:tb_DigInPort} -tclbatch tb_DigInPort.tcl -view E:/SoC/SimLab01/tb_WB_behav.wcfg -log simulate.log"
call xsim  tb_DigInPort_behav -key {Behavioral:sim_1:Functional:tb_DigInPort} -tclbatch tb_DigInPort.tcl -view E:/SoC/SimLab01/tb_WB_behav.wcfg -log simulate.log
>>>>>>> 449bf3b4ec1b282ffaddda01f6845934e50168f2
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
