set_property SRC_FILE_INFO {cfile:F:/01_SoC/MAXSONAR/MAXSONAR.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc rfile:../../../MAXSONAR.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { PWM }]; #IO_L23P_T3_35 Sch=led[0]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W8    IOSTANDARD LVCMOS33     } [get_ports { RX }]; #IO_L15N_T2_DQS_13 Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V7    IOSTANDARD LVCMOS33     } [get_ports { PWM }]; #IO_L11N_T1_SRCC_13 Sch=jb_n[2]
