set_property PACKAGE_PIN K17 [get_ports clk_i]
set_property PACKAGE_PIN Y11 [get_ports done]
set_property PACKAGE_PIN K18 [get_ports en_i]
set_property PACKAGE_PIN M14 [get_ports sclk]
set_property PACKAGE_PIN M15 [get_ports MOSI]
set_property PACKAGE_PIN G14 [get_ports busy_o]
set_property PACKAGE_PIN P16 [get_ports rstn_i]
set_property PACKAGE_PIN G15 [get_ports {data_i[7]}]
set_property PACKAGE_PIN P15 [get_ports {data_i[6]}]
set_property PACKAGE_PIN W13 [get_ports {data_i[5]}]
set_property PACKAGE_PIN T16 [get_ports {data_i[4]}]
set_property PACKAGE_PIN Y16 [get_ports {data_i[3]}]
set_property PACKAGE_PIN K19 [get_ports {data_i[2]}]
set_property PACKAGE_PIN A20 [get_ports {data_i[1]}]
set_property PACKAGE_PIN B19 [get_ports {data_i[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk_i]
set_property IOSTANDARD LVCMOS18 [get_ports done]
set_property IOSTANDARD LVCMOS18 [get_ports en_i]
set_property IOSTANDARD LVCMOS18 [get_ports MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports rstn_i]
set_property IOSTANDARD LVCMOS18 [get_ports sclk]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_i[6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_i_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_i_IBUF[0]} {data_i_IBUF[1]} {data_i_IBUF[2]} {data_i_IBUF[3]} {data_i_IBUF[4]} {data_i_IBUF[5]} {data_i_IBUF[6]} {data_i_IBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list sclk_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list MOSI_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list done_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list busy_o_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list en_i_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list clk_i_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list spi_clk]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_i_IBUF_BUFG]
